name: mychat-workflow
on:
  push:
jobs:
  mychat:
    name: mychat
    runs-on: ubuntu-latest
    steps:
      # ...
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      # run any `bun` or `bunx` command
      - run: bun install
      - run: sudo ln -s /home/tato/.bun/bin/bun /usr/bin/bun
      - run: ls -l /usr/bin/bun
      - run: sudo bun run --hot src/index-9012.tsx
      - run: bun run build
