name: mychat-workflow
on:
  push:
jobs:
  mychat:
    name: mychat
    runs-on: ubuntu-latest
    steps:
      # ...
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      # run any `bun` or `bunx` command
      - run: sudo su
      - run: sudo apt install unzip 
      - run: curl -fsSL https://bun.sh/install | bash
      - run: git clone https://github.com/toshirot/mychat.git 
      - run: ls -l
      - run: ls -l /home/
      - run: ls -l /home/linuxbrew
      - run: ls -l /home/runner/
      - run: ls -l /home/runner/runners/
      - run: ls -l /home/runner/work/
      - run: pwd
     #  - run: source /home/runner/.bashrc
     # - run: cd mychat
      - run: bun init
     # - run: cat package.json 
        env: 
          MYCHAT_CERT: ${{ secrets.MYCHAT_CERT }}
          MYCHAT_PRIV: ${{ secrets.MYCHAT_PRIV }}
      - run: bun action
      #- run: bun run --hot src/index-9012.tsx
      - run: ls -l /home/
      - run: ls -l /home/runner/
      - run: ls -l /home/runner/runners/
      # - run: bun action
      - run: bun run build
