name: mychat-workflow
on:
  push:
jobs:
  mychat:
    name: mychat
    runs-on: ubuntu-latest
    steps:
      # ...
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      # run any `bun` or `bunx` command
      - run: sudo su
      - run: sudo apt install unzip 
      - run: curl -fsSL https://bun.sh/install | bash
      - run: git clone https://github.com/toshirot/mychat.git
      - run: ls -l /home/
      - run: ls -l /home/linuxbrew
      - run: ls -l /home/runner/
      - run: ls -l /home/runner/runners/
     #  - run: source /home/runner/.bashrc
      - run: cd mychat
      - run: bun init
      - run: cat package.json
      - run: bun dev
      - run: ls -l /home/
      - run: ls -l /home/runner/
      - run: ls -l /home/runner/runners/
      - run: bun run --hot ~/bun/elysia/mychat/src/index-9012.tsx
      - run: bun run build
